### ISSUE TITLE
JavaScript Course: Introduce JSON before Todo List project

### ISSUE THREAD

**Issue by Ariech** [TheOdinProject/curriculum#26646]
### Describe your suggestion

In the Todo List project, we were assigned the task of creating local storage using JSON, a concept we had never been introduced to before. The first mention of working with JSON comes after completing the said project. It seems that it would be more beneficial to first familiarize us with JSON and only then assign us to work with it. If changes were made, the description of the Todo List project would need to be adjusted slightly, particularly the local storage step.

JSON lesson: https://www.theodinproject.com/lessons/node-path-javascript-json

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-todo-list

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Yaess

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone review.

**Comment by JoshDevHub** [comment]
Thank you for making this issue @Ariech 

We agree that the JSON lesson could move up for the reasons you've stated. A PR to address this issue should:
- [ ] Move the JSON lesson from the `asynchronous_javascript_and_apis/` directory to the `organizing_your_javascript_code/` directory.
- [ ] Edit the content in the Todo List project around `LocalStorage` so that it no longer references "learning JSON in a future lesson". With the content being moved up before Todo List, learners will no longer take this on in the future.

To fully integrate this change, another PR will have to be added to the [main site](https://github.com/TheOdinProject/theodinproject) repo to handle the ordering/grouping of lessons on the backend. If the person who picks this up also wants to do that, just let me know. Otherwise I can handle it after this change has been made in the curriculum repo.

**Comment by Ariech** [comment]
Hey @JoshDevHub, I can create a pull request for this issue concerning changes in the curriculum. However, the backend side might be a bit challenging for me at the moment.

Regarding the content change in the Todo List project, I believe updating it from: 

> - localStorage uses [JSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON) to send and store data, and when you retrieve the data, it will also be in JSON format. You will learn more about this language in a later lesson, but it doesn't hurt to get your feet wet now. Keep in mind you *cannot store functions in JSON*, so you'll have to figure out how to add methods back to your object properties once you fetch them. Good luck!

 to     

> - localStorage uses [JSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON) to send and store data, and when you retrieve the data, it will also be in JSON format. Keep in mind you *cannot store functions in JSON*, so you'll have to figure out how to add methods back to your object properties once you fetch them. Good luck!

should be sufficient.

Let me know what you think about the changes I proposed.

**Comment by JoshDevHub** [comment]
That sounds good to me @Ariech 

I'll assign this to you. Don't worry about the backend part, the team can take care of that :+1:
