### ISSUE TITLE
More on State: Tell student to do exercises in the react documentation

### ISSUE THREAD

**Issue by guudewie** [TheOdinProject/curriculum#26749]
### Describe your suggestion

I think it would be very worth it to suggest students to do the exercises at the end of the React documentation pages. They don´t take too much time, but really deepen the understanding of the read matter. This issue also concerns the prior to courses; Introduction to State, and More on State.

Even if students might do them without explicit mentioning them, I think its worth it to notice that these small challenges are really helpful. You learn more from practice then just reading.

I imagine something like "Don´t forget to do the exercises at the end of the article!"

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-more-on-state

### Checks

- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

guudewie

### (Optional) Additional Comments

TOP for the win!!
```[tasklist]
### Tasks
- [ ] Update Text in "More on State" Course
- [ ] (Optional) Update Text in "Introduction to State" Course
```

**Comment by 01zulfi** [comment]
@guudewie I think this is a sensible suggestion. I'm thinking maybe add this suggesiton early on, perhaps in [Assignment item 1 of Introduction to React lesson](https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react#assignment) se we don't have to repeat this suggestion later in the course. What do you think?

**Comment by guudewie** [comment]
In the lesson you linked, there are no challenges at the end of the react article. The first challenge is on the [JSX lesson](https://www.theodinproject.com/lessons/node-path-react-new-what-is-jsx). In this one the challenges are already mentioned. Maybe it would make sense to emphasize that for the next 5 lessons, the student should be aware of the challenges, as the articles are mainly if not only on the react website.

So instead of "Check out the challenge at the end" something like:
"for the next lessons you will spend a lot of time on the react documentation, React provides challenges in many of their articles. We will not explicitly mention them, but be sure to do them!"

**Comment by 01zulfi** [comment]
@guudewie Sounds good to me, I've assigned you the issue, please make a pull request!
